# Generated by Django 4.2.6 on 2023-10-20 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(blank=True, max_length=120)),
                ('tipo', models.CharField(choices=[('F', 'Filme'), ('S', 'Série')], default='F', max_length=1)),
                ('data_lancamento', models.DateField(default=datetime.datetime.now)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
