# Generated by Django 4.2.7 on 2023-11-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=256)),
                ('resposta', models.CharField(max_length=256)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.categoria')),
            ],
        ),
    ]
