# Generated by Django 4.2.7 on 2023-11-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_pesquisas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesquisas',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
