- hosts: [terraform-ansible]
  tasks:
    - name: Instalando o python3 e o virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes
      become: true #root permission for linux

    - name: Instalando dependencia com pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
    - name: Iniciando o projeto
      shell: ". /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/"

    - name: Alterando o hosts do settings
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: "ALLOWED_HOSTS"
        line: "ALLOWED_HOSTS = ['*']"
        backrefs: yes
#  - name: criando o arquivo
#    copy:
#      dest: /home/ubuntu/index.html
#      content: <h1>Feito com terraform e ansible</h1>
#
#  - name: criando o servidor
#    shell: "nohup busybox httpd -f -p 8080 &"
# ansible-playbook playbook.yml -u ubuntu --private-key iac-alura.pem -i hosts.yml
