// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using Alura.ByteBank.Apresentacao.Testes.PageObjects;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using Xunit;
using Xunit.Abstractions;

namespace Alura.ByteBank.Apresentacao.Testes
{
    public class SeleniumByteBankTestes : IDisposable
    {
        public static IWebDriver driver { get; private set; }
        private ITestOutputHelper output;
        private string url = "https://localhost:5001/";
        private LoginPO loginPO;
        public SeleniumByteBankTestes(ITestOutputHelper _output)
        {
            driver = new ChromeDriver();
            this.output = _output;
            this.loginPO = new LoginPO(driver);
        }

        [Fact]
        public void LogandoNoSistema()
        {
            //Arrange
            loginPO.Navegar(url + "UsuarioApps/Login");

            //Act
            loginPO.PreencherCamposELogar("andre@email.com", "senha01");
            loginPO.btnClick();
        }

        [Fact]
        public void AcessandoPaginaDaMusicDot()
        {
            //Act
            driver.Navigate().GoToUrl("https://www.musicdot.com.br/");
            //Assert
            Assert.Contains("Music", driver.Title);
            output.WriteLine(driver.Title);
        }

        [Fact]
        public void ValidaLinkLogin()
        {
            //Arrange
            driver.Navigate().GoToUrl(url);
            IWebElement linkLogin = driver.FindElement(By.LinkText("Login"));

            //Act
            linkLogin.Click();

            //Assert
            Assert.Contains("img", driver.PageSource);
        }

        [Fact]
        public void AcessarUrlAgenciaSemPermissao()
        {
            //Arrange
            driver.Navigate().GoToUrl("https://localhost:5001/Agencia/Index");
            //Act
            //Assert
            Assert.Contains("401", driver.PageSource);
        }

        public void Dispose()
        {
            driver.Quit();
        }
    }
}