// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.IE;
using Xunit;
using Xunit.Abstractions;

namespace Alura.ByteBank.Apresentacao.Testes
{
    public class SeleniumByteBankTestes : IDisposable
    {
        public IWebDriver driver { get; private set; }
        public IDictionary<String, Object> vars { get; private set; }
        public IJavaScriptExecutor js { get; private set; }
        private ITestOutputHelper output;
        public SeleniumByteBankTestes(ITestOutputHelper _output)
        {
            this.output = _output;
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<String, Object>();
        }

        [Fact]
        public void LogandoNoSistema()
        {
            driver.Navigate().GoToUrl("https://localhost:5001/");
            driver.Manage().Window.Size = new System.Drawing.Size(1294, 1032);
            driver.FindElement(By.LinkText("Login")).Click();
            driver.FindElement(By.Id("Email")).Click();
            driver.FindElement(By.Id("Email")).SendKeys("andre@email.com");
            driver.FindElement(By.Id("Senha")).Click();
            driver.FindElement(By.Id("Senha")).SendKeys("senha01");
            driver.FindElement(By.Id("btn-logar")).Click();
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.CssSelector("html")).Click();
            driver.Close();
        }

        [Fact]
        public void AcessandoPaginaDaMusicDot()
        {
            //Act
            driver.Navigate().GoToUrl("https://www.musicdot.com.br/");
            //Assert
            Assert.Contains("Music", driver.Title);
            output.WriteLine(driver.Title);
        }

        public void Dispose()
        {
            driver.Quit();
        }
    }
}